spring:
  devtools:
    restart:
      additional-paths: src/main/java

  datasource:
    url: jdbc:mysql://localhost:3305/wdd?useUnicode=true&characterEncodeing=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    suffix: .ftl

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB